# Generated by Django 4.2.16 on 2025-08-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupabaseUser',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('auth_user_id', models.UUIDField()),
                ('username', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
