# Generated by Django 4.2.16 on 2025-09-20 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_course_courseinvitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseinvitation',
            name='course',
        ),
        migrations.RemoveField(
            model_name='courseinvitation',
            name='student',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='CourseInvitation',
        ),
    ]
